name: worker

on:
  push:

jobs:
  gradually:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tune: ["precision", "frequency", "utility", "engine", "evolution"]
        elementary: ["derive", "organic", "fisherman", "enclose"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java -jar nw
